feat(ECNO-22): migracion de componente unidad
pvega95/nostos-modelismo-back-office pull request #10
Opened 2024-11-20 17:23 UTC by Antonyp24

2024-11-30 00:31 UTC, pvega95 requested changes

2024-11-30 00:31 UTC, pvega95 commented on src/app/models/unid.ts
> +export interface IUnid {
que significa unid?

2024-11-30 00:31 UTC, pvega95 commented on src/app/modules/settings/unid/unid.component.ts
> +    formatoFecha(fecha: string): string{
crea un pipe para que se reutilize

2024-11-30 00:31 UTC, pvega95 commented on src/app/modules/settings/unid/unid.service.ts
> +  createUnid(body: any): Observable<IUnidResponse> {
no se sabe el payload?

2024-12-02 22:12 UTC, Antonyp24 commented on src/app/models/unid.ts
> +export interface IUnid {
ya corregi estaba mal la traduccion de unidad

2024-12-02 23:56 UTC, Antonyp24 commented on src/app/modules/settings/unid/unid.component.ts
> +    formatoFecha(fecha: string): string{
le puse este  | date:'dd/MM/yyyy'

2024-12-03 00:30 UTC, Antonyp24 commented on src/app/modules/settings/unid/unid.service.ts
> +  createUnid(body: any): Observable<IUnidResponse> {
ya he creado nueva interface

2024-12-23 03:07 UTC, pvega95 approved these changes

2024-12-23 20:52 UTC, merged