feat(ECNO-21): se micro componente de marca
pvega95/nostos-modelismo-back-office pull request #9
Opened 2024-10-13 21:44 UTC by Antonyp24

2024-11-04 19:15 UTC, pvega95 requested changes

2024-11-04 19:15 UTC, pvega95 commented on .gitignore
Estos sobreescribe mis configuraciones personales de mi vscode , deberia mantenerse

2024-11-04 19:15 UTC, pvega95 commented on src/@fuse/services/utils/utils.service.ts
> +//import { Select } from 'app/models';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/@fuse/services/utils/utils.service.ts
> +    getIdClient(): Observable<any> {
es any?

2024-11-04 19:15 UTC, pvega95 commented on src/@fuse/services/utils/utils.service.ts
> +        //return [year, month, day].join('-');
remover comment

2024-11-04 19:15 UTC, pvega95 commented on src/@fuse/services/utils/utils.service.ts
> +      static sinEspaciosEnBlanco(control: AbstractControl) : ValidationErrors | null {
porque defines metodos en espa;ol y en algunos en ingles , usar el standar

2024-11-04 19:15 UTC, pvega95 commented on src/app/mock-api/common/navigation/data.ts
> +        id   : 'example.id',
es necesario modificar la interfaz default?

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.component.ts
> +//import { DatePipe } from '@angular/common';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.component.ts
> +//import { fuseAnimations } from '@fuse/animations';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.component.ts
> +   // animations: fuseAnimations,
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.component.ts
> +      //  private _changeDetectorRef: ChangeDetectorRef
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.component.ts
> +      //  this._changeDetectorRef.markForCheck();
remover si no es necesario

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.component.ts
> +        // this.initForm();
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.module.ts
Ya no se usa modulos en esta version

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.module.ts
Revisar syntaxis de los otros components

2024-11-04 19:15 UTC, pvega95 commented on src/app/modules/settings/brand/brand.service.ts
> +    const query = `${BrandService.BASE_URL}/${BrandService.confManagement}/brand`;
_BrandService.confManagement_
BrandService.configManagement

2024-11-04 19:15 UTC, pvega95 commented on src/app/shared/shared.module.ts
> +//import { FileUploaderModule } from './file-uploader/file-uploader.module';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/shared/shared.module.ts
> +//import { WindowModalComponent } from './window-modal/window-modal.component';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/shared/shared.module.ts
> +//import { SelectSearchComponent } from './select-search/select-search.component';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/shared/shared.module.ts
> +//import { StatusComponent } from './status/status.component';
remover

2024-11-04 19:15 UTC, pvega95 commented on src/app/utils/form.ts
> +export const parseStringSinTildes = (value: string): string => {
para que es necesario retirar las tildes ??

2024-11-04 20:17 UTC, Antonyp24 commented on src/app/mock-api/common/navigation/data.ts
> +        id   : 'example.id',
asi es para indicar que es un id

2024-11-04 20:34 UTC, Antonyp24 commented on src/app/utils/form.ts
> +export const parseStringSinTildes = (value: string): string => {
eso sirve cuando se busca un producto que lleva tildes, por experiencia vi que hay usuarios que buscan palabras sin tilde por el apuro no se acuerdan de colocarle tilde y creen que no existe la palabra

2024-11-09 23:13 UTC, pvega95 requested changes

2024-11-09 23:13 UTC, pvega95 commented on src/app/shared/shared.module.ts
> +export class SharedModule
remover , utilizar solo los imports en los componentes q los necesitan

2024-11-09 23:13 UTC, pvega95 commented on .vscode/settings.json
agregar este file a git ignore , no todos los devs queremos las misma configuracion esto debe ser personal

2024-11-17 18:49 UTC, pvega95 approved these changes

2024-11-17 18:51 UTC, merged